### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by mrekin** [AlexSciFier/neonlink#11] opened 2022-11-13 12:02 UTC
Hi!
Choosing links bookmarking app for home usage, mainly between neonlink and linkace.
Neonlink has better (more beautiful) UI ), but has some issues (in my opinion).

Add bookmark window
1. Make URL field selected to be able Ctrl+V site address without additional clicking.
2. URL field don't allow to add url without protocol section, but sometime this causes to enter 2x symbols ) `https://fb.com` vs `fb.com`. Maybe better "auto complete" url with https if protocol not entered.
3. Group field is None by default and sometime I forgot select group. After saving new link  group view opened where new link not visible. But I don't know how to make better ))
4. Neolink allows to add dublicate link.

Links window and Edit window
1. Add Groups as filter additional to Tags.
2. Add comfirmation for delete option. Now double click may cause deleting link, delete button right under mouse poiner )
3. Why URL editing not allowed?

Other
1. LinkAce has Guest mode. Guest can see selected links, but can't edit anything. This more usefull (for me) than  Nologin option 
2. May be  usefull to add some links sorting/ordering possibilities in Groups (main) window.
3. Some links not loading Title and icon automatically (because page loads dynamically as example), have to fill fieds manually. But later button "batch update" drops all my "hand hard work".  If it possible to not update manual edited bookmarks ? 
4. Empty groups also displayed. Not very usefull if i prepare a set of groups but fill them for a long time
5. Not sure if it applicable: I have 2 groups: "To read" and "Already read". A possibility to d&d/move link from one group to other will be great.

Thanks for nice app!

**Comment by AlexSciFier** [comment] 2022-11-14 05:33
HI!
Thank you for your feedback!
Linkace is an old project with a lot of great features. My project is still young and does not yet have so many functions.

Most of the things you suggested are pretty easy to implement. But I have some comments on them.

> Group field is None by default and sometime I forgot select group. After saving new link group view opened where new link not visible. But I don't know how to make better ))

An alternative to this would be to specify, for example, the first group by default. And this is not good because groups are meant to be like a dashboard with favorites links.

>Why URL editing not allowed?

It's not a bug it's a featchure☺ In my mind, when you edit the url, it becomes another bookmark.

>LinkAce has Guest mode. Guest can see selected links, but can't edit anything. This more usefull (for me) than Nologin option

In future updates i want to implement users management. With ability to set permissions to each user.

>Not sure if it applicable: I have 2 groups: "To read" and "Already read". A possibility to d&d/move link from one group to other will be great.

Not sure how to implement this, but i will think about it.

As i said, everything else is easy to fix and this will be fixed in future updates.

**Comment by mrekin** [comment] 2022-11-14 06:02
> An alternative to this would be to specify, for example, the first group by default. And this is not good because groups are meant to be like a dashboard with favorites links.

My be better open Links view in case group not selected? With ASC sorting by date.


> Not sure how to implement this, but i will think about it.

I think this is not must have feature. Groups cards looks like kanban dashboard cards and first reaction was attempt to drag&drop :)

Additionally search field can be accessible from Cards view. 

> As i said, everything else is easy to fix and this will be fixed in future updates.

Thanks!

**Comment by mrekin** [comment] 2022-11-25 09:56
Nice update (1.2.3)
Some little issue with URL autocomplete: 
1. Type google.com
2. Autocompletition updates it to https://google.com
3. Start edit URL (changing something from protocol part (expect 's') - autocompletition adds protocol again :) 
`https://ttps://google.com`

**Comment by AlexSciFier** [comment] 2022-11-25 18:41
Yeah. I don't know of better ways to add protocol to URL and i'm thinking about to remove this feature. But if you have any suggestions or some examples of better ways to implement this feature, feel free to suggest them.

**Comment by mrekin** [comment] 2022-11-25 18:49
> any suggestions

I think can be usefull:
1) Add protocol only once after typing or pasting string. All other  field editing must don't trigger protocol adding. (like set `autocompleteUsed = true` and check it on field changes)
2) Drop this flag (set to `false`) if field became empty again.

**Comment by AlexSciFier** [comment] 2022-11-27 14:42
In new update 1.2.4 URL fild autocomplete when input lose focus.

**Comment by mrekin** [comment] 2022-11-28 10:31
> In new update 1.2.4 URL fild autocomplete when input lose focus.

Works fine)
Looks like most issues from this topic fixed.

But two new founded.
1. Seems "Dashboard columns number" property does not work.  I have 5 groups, set value to 2 or 4 - nothing changes.
2. Some icons (like Github) looks not "readable" in black theme.  May be possible to add possibility to show them in inversed colors.

**Closed** 2022-11-28 17:04 UTC
Labels: enhancement
